const card = {
  cats: [
    {
      img: "cat.jpg",
      title: "Кот полосатый",
      price: 30000,
      currency: "руб",
      buy: true,
      sale: 40,
      link: "#",
      specifications: [{ color: "Коричневый окрас", age: "2 мес.", paw: 4 }],
    },
    {
      img: "cat1.jpg",
      title: "Кот полосатый",
      price: 40000,
      currency: "руб",
      buy: false,
      sale: 0,
      link: "#",
      specifications: [{ color: "Коричневый окрас", age: 4, paw: 4 }],
    },
    {
      img: "cat2.jpg",
      title: "Кот полосатый",
      price: 20000,
      currency: "руб",
      buy: true,
      sale: 0,
      link: "#",
      specifications: [{ color: "Коричневый окрас", age: 4, paw: 4 }],
    },
    {
      img: "cat.jpg",
      title: "Кот полосатый",
      price: 25000,
      currency: "руб",
      buy: true,
      sale: 0,
      link: "#",
      specifications: [{ color: "Коричневый окрас", age: 4, paw: 4 }],
    },
    {
      img: "cat2.jpg",
      title: "Кот полосатый",
      price: 30000,
      currency: "руб",
      buy: true,
      sale: 40,
      link: "#",
      specifications: [{ color: "Коричневый окрас", age: 4, paw: 4 }],
    },
    {
      img: "cat1.jpg",
      title: "Кот полосатый",
      price: 10000,
      currency: "руб",
      buy: false,
      sale: 0,
      link: "#",
      specifications: [{ color: "Коричневый окрас", age: 4, paw: 4 }],
    },
  ],
};

card.cats.sort(card.cats.price);